version: 2.1

commands:
  dependencies:
    description: "Install dependencies"
    steps:
      - run:
          name: "Install Bundler 2 if necessary"
          command: bundle --version | grep -q "version 2" || gem install bundler

      - restore_cache:
          keys:
            - gem-cache-{{ .Branch }}-{{ checksum "zoho-crm.gemspec" }}
            # fallback to using the latest cache if no exact match is found
            - gem-cache-

      - run:
          name: "Run bundle install"
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          key:
            gem-cache-{{ .Branch }}-{{ checksum "zoho-crm.gemspec" }}
          paths:
            - vendor/bundle

  rspec:
    description: "Run the RSpec test suite"
    steps:
      - run: bundle exec rspec --format progress

  standard:
    description: "Lint the code with the Standard Ruby style guide"
    steps:
      - run: bundle exec standardrb --no-fix --format progress

jobs:
  "ruby-2_6":
    docker:
      - image: circleci/ruby:2.6

    steps:
      - checkout
      - dependencies
      - rspec

  "ruby-latest":
    docker:
      - image: circleci/ruby:latest

    steps:
      - checkout
      - dependencies
      - rspec

workflows:
  version: 2
  build:
    jobs:
      - "ruby-2_6"
